[package]
name = "feed_integrity"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "feed_integrity"

[dependencies]
hdi = { workspace = true }
serde = { workspace = true, features = ["derive"] }
