name: OurBlock Hub
version: "0.2.3"
slug: ourblock-hub
description: 24/7 Neighborhood Coordination Hub
url: https://github.com/Pixel-Pilot28/OurBlock
arch:
  - aarch64
  - amd64

init: false
startup: application
boot: auto

ports:
  8099/tcp: 8099
  8888/tcp: 8888
  8001/tcp: 8001

ports_description:
  8099/tcp: Web UI
  8888/tcp: App Interface
  8001/tcp: Admin Interface

map:
  - config:rw
  - share:rw

options:
  log_level: info

schema:
  log_level: str
