[package]
name = "events"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "events"

[dependencies]
hdk = { workspace = true }
events_integrity = { path = "../../integrity/events" }
serde = { workspace = true, features = ["derive"] }
