[package]
name = "file_storage_integrity"
version = "0.1.0"
edition = "2021"

[dependencies]
hdi = { workspace = true }
serde = { workspace = true }
serde_bytes = "0.11"
holochain_serialized_bytes = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]
